spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/airesearchdb

# Server Configuration
server.port=8081
gemini.api.key=AQ.Ab8RN6IwCZ-EhgO418i70SNtuIBRTXIAZKq0IFFzzu8nyVXaTggit 